import { Map, Coffee, Compass, Star } from "lucide-react";
import Image from "next/image";

export default function Community() {
  const trendingTrips = [
    {
      id: 1,
      title: "Neon Nights in Tokyo",
      author: "@alex_explore",
      image: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80",
      likes: 1243,
      tags: ["Party", "Urban", "High Budget"]
    },
    {
      id: 2,
      title: "Serenity in Santorini",
      author: "@mia.travels",
      image: "https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=800&q=80",
      likes: 980,
      tags: ["Romantic", "Luxury", "Chill"]
    },
    {
      id: 3,
      title: "Backpacking the Alps",
      author: "@mountain_hiker",
      image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80",
      likes: 850,
      tags: ["Adventure", "Budget", "Explore"]
    }
  ];

  return (
    <main className="max-w-7xl mx-auto px-4 py-24 relative z-10 w-full">
      <div className="text-center mb-16">
        <h1 className="text-4xl md:text-5xl font-extrabold mb-4">
          Community <span className="text-gradient">Journeys</span>
        </h1>
        <p className="text-white/60 max-w-2xl mx-auto text-lg">
          Discover hand-crafted itineraries generated by our AI and curated by travelers like you.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
        {trendingTrips.map((trip) => (
          <div key={trip.id} className="glass rounded-3xl overflow-hidden border border-white/5 hover:border-[#7C5CFF]/30 transition-all group">
            <div className="relative h-64 w-full overflow-hidden">
              <img 
                src={trip.image} 
                alt={trip.title} 
                className="w-full h-full object-cover group-hover:scale-110 transition-transform duration-700"
              />
              <div className="absolute inset-0 bg-gradient-to-t from-[#121826] to-transparent" />
              <div className="absolute bottom-4 left-4 right-4">
                <h3 className="text-xl font-bold mb-1">{trip.title}</h3>
                <p className="text-sm text-white/70">by {trip.author}</p>
              </div>
            </div>
            
            <div className="p-6">
              <div className="flex flex-wrap gap-2 mb-4">
                {trip.tags.map((tag, i) => (
                  <span key={i} className="text-xs font-medium px-2 py-1 rounded-md bg-white/5 border border-white/10 text-white/70">
                    {tag}
                  </span>
                ))}
              </div>
              
              <div className="flex justify-between items-center pt-4 border-t border-white/10">
                <div className="flex items-center gap-1 text-white/50 hover:text-[#FF7AD9] transition-colors cursor-pointer">
                  <Star className="w-5 h-5" />
                  <span className="text-sm">{trip.likes}</span>
                </div>
                <button className="text-sm font-semibold text-[#00D4FF] hover:unwrap">
                  View Itinerary
                </button>
              </div>
            </div>
          </div>
        ))}
      </div>
    </main>
  );
}
